## Test html ##

<table>
    <tr>
        <td>Foo</td>
    </tr>
</table>


<script type="application/json" data-for="htmlwidget-00e9082436f743fee922">{"x":{"data":[{"x":[2734,2725,2210,2137,2109,2044,2003,1981],"y":[0.7,1.7,2.7,3.7,4.7,5.7,6.7,7.7],"text":["Runs: 2734<br>Result: All<br>Team:  Mumbai Indians","Runs: 2725<br>Result: All<br>Team:  Chennai Super Kings","Runs: 2210<br>Result: All<br>Team:  Sunrisers Hyderabad","Runs: 2137<br>Result: All<br>Team:  Rajasthan Royals","Runs: 2109<br>Result: All<br>Team:  Royal Challengers Bangalore","Runs: 2044<br>Result: All<br>Team:  Kolkata Knight Riders","Runs: 2003<br>Result: All<br>Team:  Kings XI Punjab","Runs: 1981<br>Result: All<br>Team:  Delhi Daredevils"],"key":null,"type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"All","legendgroup":"All","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","orientation":"h"},{"x":[1711,1634,1239,1189,1251,1167,474,765],"y":[1,2,3,4,5,6,7,8],"text":["Runs: 1711<br>Result: Won<br>Team:  Mumbai Indians","Runs: 1634<br>Result: Won<br>Team:  Chennai Super Kings","Runs: 1239<br>Result: Won<br>Team:  Sunrisers Hyderabad","Runs: 1189<br>Result: Won<br>Team:  Rajasthan Royals","Runs: 1251<br>Result: Won<br>Team:  Royal Challengers Bangalore","Runs: 1167<br>Result: Won<br>Team:  Kolkata Knight Riders","Runs: 474<br>Result: Won<br>Team:  Kings XI Punjab","Runs: 765<br>Result: Won<br>Team:  Delhi Daredevils"],"key":null,"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Won","legendgroup":"Won","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","orientation":"h"},{"x":[1023,1091,971,948,858,877,1529,1216],"y":[1.3,2.3,3.3,4.3,5.3,6.3,7.3,8.3],"text":["Runs: 1023<br>Result: Lost<br>Team:  Mumbai Indians","Runs: 1091<br>Result: Lost<br>Team:  Chennai Super Kings","Runs: 971<br>Result: Lost<br>Team:  Sunrisers Hyderabad","Runs: 948<br>Result: Lost<br>Team:  Rajasthan Royals","Runs: 858<br>Result: Lost<br>Team:  Royal Challengers Bangalore","Runs: 877<br>Result: Lost<br>Team:  Kolkata Knight Riders","Runs: 1529<br>Result: Lost<br>Team:  Kings XI Punjab","Runs: 1216<br>Result: Lost<br>Team:  Delhi Daredevils"],"key":null,"type":"bar","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Lost","legendgroup":"Lost","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","orientation":"h"}],"layout":{"margin":{"t":82.4876790774752,"r":18.8976377952756,"b":56.7556701738559,"l":238.075719987056},"plot_bgcolor":"rgba(248,242,228,1)","paper_bgcolor":"rgba(248,242,228,1)","font":{"color":"rgba(0,0,0,1)","family":"helvetica","size":15.9402241594022},"title":"<b> Total Runs scored by the Teams \u003c/b>","titlefont":{"color":"rgba(0,0,0,1)","family":"helvetica","size":28.692403486924},"xaxis":{"domain":[0,1],"type":"linear","autorange":false,"tickmode":"array","range":[-136.7,2870.7],"ticktext":["0","1000","2000"],"tickvals":[0,1000,2000],"ticks":"outside","tickcolor":"rgba(0,0,0,1)","ticklen":3.98505603985056,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(0,0,0,1)","family":"helvetica","size":15.9402241594022},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"y","title":"Runs","titlefont":{"color":"rgba(0,0,0,1)","family":"helvetica","size":17.9327521793275},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"type":"linear","autorange":false,"tickmode":"array","range":[0.4,8.6],"ticktext":["Mumbai Indians","Chennai Super Kings","Sunrisers Hyderabad","Rajasthan Royals","Royal Challengers Bangalore","Kolkata Knight Riders","Kings XI Punjab","Delhi Daredevils"],"tickvals":[1,2,3,4,5,6,7,8],"ticks":"","tickcolor":null,"ticklen":3.98505603985056,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(0,0,0,1)","family":"helvetica","size":15.9402241594022},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(0,0,0,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"helvetica","size":17.9327521793275},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"transparent","width":0.66417600664176,"linetype":"none"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(248,242,228,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"helvetica","size":12.7521793275218},"y":0.819065170045234},"annotations":[{"text":"Result","x":1.02,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"helvetica","size":23.9103362391034},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"left","yanchor":"top","legendTitle":true}],"barmode":"stack","bargap":0,"hovermode":"closest"},"source":"A"},"evals":[],"jsHooks":[]}</script>
<script type="application/htmlwidget-sizing" data-for="htmlwidget-00e9082436f743fee922">{"viewer":{"width":"100%","height":400,"padding":15,"fill":true},"browser":{"width":"100%","height":400,"padding":40,"fill":true}}</script>